### ISSUE TITLE
返回按钮修改

### ISSUE THREAD

**Issue by DK3369** [xiaoyouPrince/XYNav#1]
var backImage: UIImage? = nil
除了这种方法，还有没有更简单的，一次性弄好的 返回按钮图片
self.navigationItem.leftBarButtonItem = UIBarButtonItem(image: UIImage(named: "top_back"), style: .plain, target: self, action: #selector(back))

返回按钮图片修改后，这个tintColor 会变色
UINavigationBar.appearance().tintColor = .none

**Comment by xiaoyouPrince** [comment]
第一个问题
当前版本中没有开放一键设置全局返回图片功能

但是你可以用以下方法实现
1. 定义控制器基类，基类中统一设置导航控制器。 这个方法最简单
2. 使用 OC 的Runtime，hook 控制器的 viewDidLoad 方法去统一设置 VC 的返回图片。此方法涉及 OC 混编，不建议
3. 自行拓展 XYNav 源码。此方法打破了抽取导航栏的初衷，不建议

此需求我可能会在后面版本中提供统一设置的方法


第二个问题
关于修改返回图片， tintColor 会变色，我尝试写 Demo 并未复现。方便的话你可以发一下你的 Demo


最后：欢迎你使用 XYNav，欢迎你提出使用过程中的不足，也欢迎你为 XYNav 提交代码，共同让 XYNav 更好用
